-- Election atlas: Testland. Generated by scripts/atlas/build_sql.py from the files in "testland".
-- Do not edit by hand: change the files and build it again. Every statement upserts,
-- so running it again changes nothing.

-- atlas_areas: 5 rows
insert into public.atlas_areas (key, level, name, parent, iebc_code) values
  ('testland', 'county', 'Testland', 'kenya', '901')
on conflict (key) do update set level = excluded.level, name = excluded.name, parent = excluded.parent, iebc_code = excluded.iebc_code;
insert into public.atlas_areas (key, level, name, parent, iebc_code) values
  ('testland/north-test', 'constituency', 'North Test', 'testland', '9101'),
  ('testland/south-test', 'constituency', 'South Test', 'testland', null)
on conflict (key) do update set level = excluded.level, name = excluded.name, parent = excluded.parent, iebc_code = excluded.iebc_code;
insert into public.atlas_areas (key, level, name, parent, iebc_code) values
  ('testland/north-test/ward-one', 'ward', 'Ward One', 'testland/north-test', null),
  ('testland/north-test/ward-two', 'ward', 'Ward Two', 'testland/north-test', null)
on conflict (key) do update set level = excluded.level, name = excluded.name, parent = excluded.parent, iebc_code = excluded.iebc_code;

-- atlas_candidates: 8 rows
insert into public.atlas_candidates (id, election_id, seat, name, party, bloc) values
  ('2022-governor/testland/a-test', '2022-governor', 'testland', 'A Test', 'Party A', 'Alpha'),
  ('2022-governor/testland/b-test', '2022-governor', 'testland', 'B Test', 'Party B', 'Beta'),
  ('2022-governor/testland/wa-test-jr', '2022-governor', 'testland', 'Wa Test, Jr.', 'Party "C"', 'Gamma'),
  ('2022-mp/testland/north-test/m-one-test', '2022-mp', 'testland/north-test', 'M One Test', 'Party A', 'Alpha'),
  ('2022-mp/testland/north-test/m-two-test', '2022-mp', 'testland/north-test', 'M Two Test', 'Party B', 'Beta'),
  ('2022-mp/testland/north-test/otest', '2022-mp', 'testland/north-test', 'O''Test', null, 'Independent'),
  ('2022-president/kenya/p-one-test', '2022-president', 'kenya', 'P One Test', 'Party A', 'Alpha'),
  ('2022-president/kenya/p-two-test', '2022-president', 'kenya', 'P Two Test', 'Party B', 'Beta')
on conflict (id) do update set election_id = excluded.election_id, seat = excluded.seat, name = excluded.name, party = excluded.party, bloc = excluded.bloc;

-- atlas_results: 18 rows
insert into public.atlas_results (candidate_id, area_key, votes) values
  ('2022-governor/testland/a-test', 'testland', 600),
  ('2022-governor/testland/a-test', 'testland/north-test', 350),
  ('2022-governor/testland/a-test', 'testland/south-test', 250),
  ('2022-governor/testland/b-test', 'testland', 300),
  ('2022-governor/testland/b-test', 'testland/north-test', 100),
  ('2022-governor/testland/b-test', 'testland/south-test', 200),
  ('2022-governor/testland/wa-test-jr', 'testland', 100),
  ('2022-governor/testland/wa-test-jr', 'testland/north-test', 40),
  ('2022-governor/testland/wa-test-jr', 'testland/south-test', 60),
  ('2022-mp/testland/north-test/m-one-test', 'testland/north-test', 350),
  ('2022-mp/testland/north-test/m-two-test', 'testland/north-test', 150),
  ('2022-mp/testland/north-test/otest', 'testland/north-test', 0),
  ('2022-president/kenya/p-one-test', 'testland', 550),
  ('2022-president/kenya/p-one-test', 'testland/north-test', 300),
  ('2022-president/kenya/p-one-test', 'testland/south-test', 250),
  ('2022-president/kenya/p-two-test', 'testland', 450),
  ('2022-president/kenya/p-two-test', 'testland/north-test', 250),
  ('2022-president/kenya/p-two-test', 'testland/south-test', 200)
on conflict (candidate_id, area_key) do update set votes = excluded.votes;

-- atlas_turnout: 8 rows
insert into public.atlas_turnout (election_id, area_key, registered, cast_votes, rejected_votes, valid_votes, source, source_url) values
  ('2017-mp', 'testland/north-test', 1000, null, null, null, 'IEBC, MP results by constituency 2017', null),
  ('2022-governor', 'testland', 2000, 1020, 20, 1000, 'IEBC, Governor results by constituency 2022', 'https://example.test/governor-2022'),
  ('2022-governor', 'testland/north-test', 1100, 500, 10, 490, 'IEBC, Governor results by constituency 2022', 'https://example.test/governor-2022'),
  ('2022-governor', 'testland/south-test', 900, 520, 10, 510, 'IEBC, Governor results by constituency 2022', 'https://example.test/governor-2022'),
  ('2022-mp', 'testland/north-test', 1100, 510, 10, 500, 'IEBC, MP results by constituency 2022', 'https://example.test/mp-2022'),
  ('2022-president', 'testland', 2000, 1020, 20, 1000, 'IEBC, Presidential results by constituency 2022', 'https://example.test/president-2022'),
  ('2022-president', 'testland/north-test', 1100, 560, 10, 550, 'IEBC, Presidential results by constituency 2022', 'https://example.test/president-2022'),
  ('2022-president', 'testland/south-test', 900, 460, 10, 450, 'IEBC, Presidential results by constituency 2022', 'https://example.test/president-2022')
on conflict (election_id, area_key) do update set registered = excluded.registered, cast_votes = excluded.cast_votes, rejected_votes = excluded.rejected_votes, valid_votes = excluded.valid_votes, source = excluded.source, source_url = excluded.source_url;

-- atlas_register: 6 rows
insert into public.atlas_register (year, area_key, registered, source, source_url) values
  (2017, 'testland/north-test/ward-one', 550, 'IEBC, Registered voters by ward 2017', 'https://example.test/register-2017'),
  (2022, 'testland', 2000, 'IEBC, Registered voters by ward 2022', 'https://example.test/register-2022'),
  (2022, 'testland/north-test', 1100, 'IEBC, Registered voters by ward 2022', 'https://example.test/register-2022'),
  (2022, 'testland/north-test/ward-one', 600, 'IEBC, Registered voters by ward 2022', 'https://example.test/register-2022'),
  (2022, 'testland/north-test/ward-two', 500, 'IEBC, Registered voters by ward 2022', 'https://example.test/register-2022'),
  (2022, 'testland/south-test', 900, 'IEBC, Registered voters by ward 2022', 'https://example.test/register-2022')
on conflict (year, area_key) do update set registered = excluded.registered, source = excluded.source, source_url = excluded.source_url;

-- atlas_population: 2 rows
insert into public.atlas_population (area_key, year, total, adults, young_adults, source, method) values
  ('testland/north-test/ward-one', 2025, 1500, 900, 400, 'WorldPop, Age and sex structures (test)', 'Test estimate from the age-and-sex grid'),
  ('testland/north-test/ward-two', 2025, 1300, 800, 350, 'WorldPop, Age and sex structures (test)', 'Test estimate from the age-and-sex grid')
on conflict (area_key, year) do update set total = excluded.total, adults = excluded.adults, young_adults = excluded.young_adults, source = excluded.source, method = excluded.method;
