// Demo: a governor's campaign in Nairobi. Figures are invented for the demo
// except the 2022 top two, which are IEBC's. Rivals are placeholders.

import { hashOf, seeded } from "@/lib/demo/insights";
import type { AreaModel, Scenario } from "@/lib/demo/types";

// constituency, registered (approx.), our share, Challenger A, Challenger B,
// turnout 2027, turnout 2022, our 2022 share, hours to results, wards [slug, name]
type Row = [
  string,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  [string, string][],
];

const ROWS: Row[] = [
  [
    "Westlands",
    160_000,
    55,
    37,
    7,
    0.5,
    0.45,
    57,
    0.4,
    [
      ["kangemi", "Kangemi"],
      ["karura", "Karura"],
      ["kitisuru", "Kitisuru"],
      ["mountain-view", "Mountain View"],
      ["parklands-highridge", "Parklands/Highridge"],
    ],
  ],
  [
    "Dagoretti North",
    150_000,
    49,
    43,
    7,
    0.52,
    0.48,
    52,
    0.4,
    [
      ["gatina", "Gatina"],
      ["kabiro", "Kabiro"],
      ["kawangware", "Kawangware"],
      ["kileleshwa", "Kileleshwa"],
      ["kilimani", "Kilimani"],
    ],
  ],
  [
    "Dagoretti South",
    150_000,
    46,
    46,
    7,
    0.55,
    0.52,
    50,
    0.6,
    [
      ["mutu-ini", "Mutu-ini"],
      ["ngando", "Ngando"],
      ["riruta", "Riruta"],
      ["uthiru-ruthimitu", "Uthiru/Ruthimitu"],
      ["waithaka", "Waithaka"],
    ],
  ],
  [
    "Langata",
    150_000,
    52,
    41,
    6,
    0.53,
    0.5,
    55,
    0.5,
    [
      ["karen", "Karen"],
      ["mugumo-ini", "Mugumo-ini"],
      ["nairobi-west", "Nairobi West"],
      ["nyayo-highrise", "Nyayo Highrise"],
      ["south-c", "South C"],
    ],
  ],
  [
    "Kibra",
    115_000,
    39,
    54,
    6,
    0.6,
    0.57,
    40,
    0.5,
    [
      ["laini-saba", "Laini Saba"],
      ["lindi", "Lindi"],
      ["makina", "Makina"],
      ["sarangombe", "Sarangombe"],
      ["woodley-kenyatta-golf-course", "Woodley/Kenyatta Golf Course"],
    ],
  ],
  [
    "Roysambu",
    170_000,
    53,
    40,
    6,
    0.57,
    0.54,
    60,
    0.6,
    [
      ["githurai", "Githurai"],
      ["kahawa", "Kahawa"],
      ["kahawa-west", "Kahawa West"],
      ["roysambu", "Roysambu"],
      ["zimmerman", "Zimmerman"],
    ],
  ],
  [
    "Kasarani",
    175_000,
    54,
    39,
    6,
    0.58,
    0.55,
    60,
    0.7,
    [
      ["clay-city", "Clay City"],
      ["kasarani", "Kasarani"],
      ["mwiki", "Mwiki"],
      ["njiru", "Njiru"],
      ["ruai", "Ruai"],
    ],
  ],
  [
    "Ruaraka",
    125_000,
    45,
    48,
    6,
    0.58,
    0.55,
    50,
    0.6,
    [
      ["baba-dogo", "Baba Dogo"],
      ["korogocho", "Korogocho"],
      ["lucky-summer", "Lucky Summer"],
      ["mathare-north", "Mathare North"],
      ["utalii", "Utalii"],
    ],
  ],
  [
    "Embakasi South",
    165_000,
    43,
    50,
    6,
    0.58,
    0.55,
    48,
    0.7,
    [
      ["imara-daima", "Imara Daima"],
      ["kwa-njenga", "Kwa Njenga"],
      ["kwa-reuben", "Kwa Reuben"],
      ["kware", "Kware"],
      ["pipeline", "Pipeline"],
    ],
  ],
  [
    "Embakasi North",
    130_000,
    47,
    46,
    6,
    0.59,
    0.56,
    52,
    0.6,
    [
      ["dandora-area-i", "Dandora Area I"],
      ["dandora-area-ii", "Dandora Area II"],
      ["dandora-area-iii", "Dandora Area III"],
      ["dandora-area-iv", "Dandora Area IV"],
      ["kariobangi-north", "Kariobangi North"],
    ],
  ],
  [
    "Embakasi Central",
    150_000,
    45,
    48,
    6,
    0.59,
    0.56,
    50,
    0.7,
    [
      ["kayole-central", "Kayole Central"],
      ["kayole-north", "Kayole North"],
      ["kayole-south", "Kayole South"],
      ["komarock", "Komarock"],
      ["matopeni-spring-valley", "Matopeni/Spring Valley"],
    ],
  ],
  [
    "Embakasi East",
    170_000,
    53,
    40,
    6,
    0.57,
    0.54,
    58,
    0.8,
    [
      ["embakasi", "Embakasi"],
      ["lower-savannah", "Lower Savannah"],
      ["mihango", "Mihango"],
      ["upper-savannah", "Upper Savannah"],
      ["utawala", "Utawala"],
    ],
  ],
  [
    "Embakasi West",
    145_000,
    48,
    45,
    6,
    0.58,
    0.55,
    52,
    0.6,
    [
      ["kariobangi-south", "Kariobangi South"],
      ["mowlem", "Mowlem"],
      ["umoja-i", "Umoja I"],
      ["umoja-ii", "Umoja II"],
    ],
  ],
  [
    "Makadara",
    125_000,
    49,
    44,
    6,
    0.57,
    0.54,
    54,
    0.5,
    [
      ["harambee", "Harambee"],
      ["makongeni", "Makongeni"],
      ["maringo-hamza", "Maringo/Hamza"],
      ["viwandani", "Viwandani"],
    ],
  ],
  [
    "Kamukunji",
    115_000,
    40,
    53,
    6,
    0.56,
    0.53,
    45,
    0.4,
    [
      ["airbase", "Airbase"],
      ["california", "California"],
      ["eastleigh-north", "Eastleigh North"],
      ["eastleigh-south", "Eastleigh South"],
      ["pumwani", "Pumwani"],
    ],
  ],
  [
    "Starehe",
    130_000,
    50,
    43,
    6,
    0.54,
    0.51,
    53,
    0.3,
    [
      ["landimawe", "Landimawe"],
      ["nairobi-central", "Nairobi Central"],
      ["nairobi-south", "Nairobi South"],
      ["ngara", "Ngara"],
      ["pangani", "Pangani"],
      ["ziwani-kariokor", "Ziwani/Kariokor"],
    ],
  ],
  [
    "Mathare",
    125_000,
    38,
    55,
    6,
    0.6,
    0.57,
    42,
    0.5,
    [
      ["hospital", "Hospital"],
      ["huruma", "Huruma"],
      ["kiamaiko", "Kiamaiko"],
      ["mabatini", "Mabatini"],
      ["mlango-kubwa", "Mlango Kubwa"],
      ["ngei", "Ngei"],
    ],
  ],
];

const round1 = (n: number) => Math.round(n * 10) / 10;

/** Each ward varies a little around its constituency, the same way every time. */
const areas: AreaModel[] = ROWS.flatMap(
  ([group, registered, us, a, b, turnout, turnout2022, us2022, lag, wards]) =>
    wards.map(([slug, name]) => {
      const r = seeded(hashOf(slug));
      const tilt = (r() - 0.5) * 7;
      return {
        slug,
        name,
        group,
        registered: Math.round(((registered / wards.length) * (0.8 + 0.4 * r())) / 10) * 10,
        shares: { us: round1(us + tilt), a: round1(a - tilt), b },
        turnout: round1((turnout + (r() - 0.5) * 0.06) * 100) / 100,
        turnout2022: round1((turnout2022 + (r() - 0.5) * 0.06) * 100) / 100,
        us2022: round1(us2022 + (r() - 0.5) * 6),
        lag: round1(lag + r() * 0.4),
      };
    }),
);

export const sakaja: Scenario = {
  key: "sakaja",
  office: "governor",
  officeLabel: "Governor",
  seat: "Nairobi County",
  candidate: {
    name: "Johnson Sakaja",
    first: "Johnson",
    initials: "JS",
    party: "UDA",
    fictional: false,
  },
  contenders: [
    { key: "us", name: "Johnson Sakaja", party: "UDA", tone: "us", us: true },
    { key: "a", name: "Challenger A", party: "Opposition coalition", tone: "a" },
    { key: "b", name: "Challenger B", party: "Independent", tone: "b" },
  ],
  geo: { file: "/geo/nairobi-wards.json", unit: "ward", units: "wards", group: "Constituency" },
  areas,
  winNumber: { target: 620_000, found: 412_380 },
  today: [
    {
      title: "Be seen in Kayole before noon",
      detail:
        "The water story is running on Challenger A's terms. Standing at a water point with the bowser timetable changes the picture on the evening news.",
      action: {
        kind: "task",
        label: "Add to today's diary",
        task: "Kayole water point visit, 11:00, with the bowser schedule",
      },
    },
    {
      title: "Unblock the Gikomba traders' meeting",
      detail:
        "They asked for a meeting on stall allocation nine days ago. Kamukunji is where you trail by 13, and traders talk to every customer.",
      action: {
        kind: "task",
        label: "Confirm for Thursday",
        task: "Confirm the Gikomba traders' meeting for Thursday 12:00",
      },
    },
    {
      title: "Sign off drainage crews before the rains",
      detail:
        "The short rains may come two weeks early. Nine wards flooded last season; a published schedule gets ahead of the photos.",
      action: {
        kind: "draft",
        label: "Draft the schedule notice",
        title: "Drainage before the rains",
        body: "From Monday, county crews will clear drains in the nine wards that flooded last season, estate by estate. The full schedule is on the county website and at every ward office. If your drain is blocked, SMS the word DRAIN and your estate to our number and a crew will come within 72 hours.",
      },
    },
  ],
  story: {
    tag: "County",
    kicker: "Water · Eastlands",
    headline: "Water rationing extended in 14 Eastlands wards for three more weeks",
    summary:
      "Low dam levels and a burst main have cut supply to about 1.1 million residents. Vendors are charging KES 30 a jerrican in Kayole and Umoja.",
    numbers: [
      { value: "14", label: "wards on rationing; 9 are on your swing list" },
      { value: "380k", label: "registered voters affected" },
      { value: "3.4×", label: "water complaints in the inbox against last week" },
    ],
    rivals:
      'Challenger A filmed a tanker queue in Kayole last night (61,000 views) and is promising "a tap in every plot". Challenger B hasn\'t engaged.',
    line: "Own it and show the plan: publish the rationing timetable estate by estate, send free bowsers to the 14 wards from tomorrow, and give a date for the repair. Say it from Kayole, not City Hall.",
    actions: [
      { kind: "go", label: "Send canvassers to the 14 wards", to: "/canvassing" },
      {
        kind: "poll",
        label: "Ask Eastlands when water last came",
        ask: "When did water last come out of your tap?",
      },
    ],
    source: "Inbox, listening and utility notices (demo)",
    time: "05:55",
  },
  news: [
    {
      tag: "County",
      headline:
        "County Assembly schedules the finance bill debate for Tuesday, with new parking fees",
      soWhat:
        "Matatu owners and traders will mobilise. Have your line on fees ready before Monday.",
      source: "County Assembly order paper (demo)",
      time: "Yesterday 17:20",
    },
    {
      tag: "Opponent",
      headline: "Challenger A launches a clean-up drive in Eastleigh with 40 youth groups",
      soWhat:
        "Garbage is the second issue in Kamukunji and Starehe, and 23 of those groups worked with your campaign in 2022.",
      source: "Media monitoring",
      time: "Yesterday",
    },
    {
      tag: "Local",
      headline: "Matatu operators threaten a strike over new CBD termini",
      soWhat: "A weekday strike hits 1.2M commuters, and the termini decision is the county's.",
      source: "Operators' association statement (demo)",
      time: "07:10",
      action: {
        kind: "poll",
        label: "Ask commuters",
        ask: "Where should matatus from your route stop in town?",
      },
    },
    {
      tag: "Party",
      headline: "Your party publishes its 2027 nomination timetable",
      soWhat:
        "Governor nominations close in March. MCA aspirants in 11 wards are already asking for your endorsement.",
      source: "Party secretariat",
      time: "Yesterday 19:00",
    },
    {
      tag: "Security",
      headline: "Extra police patrols in Kibra after a run of phone thefts",
      soWhat:
        "Security is Kibra's third issue. A joint walk with the area police commander would land well.",
      source: "Police statement (demo)",
      time: "06:30",
    },
  ],
  polls: {
    average: [
      { week: "10 Jul", shares: { us: 41, a: 40, b: 7, undecided: 12 } },
      { week: "17 Jul", shares: { us: 41, a: 40, b: 7, undecided: 12 } },
      { week: "24 Jul", shares: { us: 42, a: 40, b: 7, undecided: 11 } },
      { week: "31 Jul", shares: { us: 42, a: 40, b: 6, undecided: 12 } },
      { week: "7 Aug", shares: { us: 43, a: 39, b: 6, undecided: 12 } },
      { week: "14 Aug", shares: { us: 43, a: 39, b: 6, undecided: 12 } },
      { week: "21 Aug", shares: { us: 44, a: 39, b: 6, undecided: 11 } },
      { week: "28 Aug", shares: { us: 44, a: 40, b: 6, undecided: 10 } },
      { week: "4 Sep", shares: { us: 45, a: 40, b: 6, undecided: 9 } },
      { week: "11 Sep", shares: { us: 45, a: 40, b: 6, undecided: 9 } },
      { week: "18 Sep", shares: { us: 44, a: 41, b: 6, undecided: 9 } },
      { week: "25 Sep", shares: { us: 44, a: 41, b: 6, undecided: 9 } },
    ],
    own: {
      date: "21–23 Sep",
      method: "SMS and USSD panel, weighted by constituency, age and sex",
      n: 2380,
      moe: 2,
      question: "If the governor election were held today, who would you vote for?",
      shares: { us: 44, a: 41, b: 6, undecided: 9 },
    },
    outside: [
      {
        pollster: "Pollster A",
        date: "16 Sep",
        n: 1200,
        shares: { us: 43, a: 42, b: 6, undecided: 9 },
      },
      {
        pollster: "Pollster B",
        date: "6 Sep",
        n: 1000,
        shares: { us: 45, a: 40, b: 5, undecided: 10 },
      },
    ],
    crosstabs: [
      { group: "Women 35+", us: 51, rival: 37, note: "Your base, and water is their first issue." },
      { group: "Men 18–24", us: 36, rival: 45, note: "Challenger A leads on jobs and policing." },
      { group: "Eastlands", us: 41, rival: 47, note: "The water story is costing you here." },
      {
        group: "Westlands & Kilimani",
        us: 55,
        rival: 33,
        note: "Safe, but turnout was 41% in 2022.",
      },
    ],
    ideas: [
      "When did water last come out of your tap?",
      "Which one thing should City Hall fix first in your estate?",
      "Would you pay a daily fee for a secure hawking spot?",
    ],
  },
  opponents: [
    {
      key: "a",
      yesterday: "Kayole and Umoja: filmed a tanker queue, then two church youth meetings.",
      message: 'Water and jobs: "a tap in every plot".',
      voice: 38,
      spend: "≈ KES 2.4M this week on Facebook and matatu branding (estimate)",
      threat: "high",
      watch: "He is in Mathare North tonight. Your ward coordinator should be at the same event.",
    },
    {
      key: "b",
      yesterday: "A Twitter Space on the county budget (14,000 listeners).",
      message: "Publish every county tender.",
      voice: 11,
      spend: "Low",
      threat: "low",
      watch:
        "He is pulling professionals in Westlands. Launching the tender portal would take the issue.",
    },
  ],
  voters: {
    issues: [
      { label: "Water", share: 28, change: 6, hot: "Kayole, Umoja, Embakasi" },
      { label: "Garbage", share: 18, change: 1, hot: "Kamukunji, Starehe, Mathare" },
      { label: "Jobs", share: 16, change: 0, hot: "Kibra, Mathare" },
      { label: "Roads & traffic", share: 12, change: -1, hot: "Kasarani, Roysambu" },
      { label: "Hawkers & market fees", share: 9, change: 2, hot: "CBD, Gikomba" },
      { label: "Security", share: 8, change: 1, hot: "Kibra, Dandora" },
    ],
    groups: [
      {
        label: "Women 35+ in Eastlands",
        size: "260k voters",
        move: -4,
        note: "Water: the biggest single swing this month.",
      },
      {
        label: "Traders & hawkers",
        size: "310k",
        move: -3,
        note: "Market fees and stall allocation; Gikomba is the test.",
      },
      {
        label: "Young professionals",
        size: "220k",
        move: 2,
        note: "Like the digital permits. 41% turnout in 2022.",
      },
      {
        label: "Church youth networks",
        size: "90k",
        move: 1,
        note: "Organised, and they turn out.",
      },
    ],
    quotes: [
      {
        text: "Maji imekuwa shida tangu Agosti. Tunanunua jerrican kwa thirty bob.",
        translation:
          "Water has been a problem since August. We buy a jerrican for thirty shillings.",
        who: "Woman, 41",
        where: "Kayole · SMS reply",
      },
      {
        text: "Parking ni sawa, lakini tutauza wapi?",
        translation: "Parking is fine, but where will we sell?",
        who: "Hawker, 29",
        where: "CBD · canvass note",
      },
      {
        text: "The roads in Kasarani are better. Now fix the street lights.",
        who: "Man, 37",
        where: "Kasarani · web poll comment",
      },
    ],
    persuadables: {
      count: 238_000,
      note: "Undecided or soft, in wards where the last margin was under 5 points. 58% of them live in Eastlands.",
    },
  },
  lastTime: {
    title: "2022 governor election, Nairobi",
    official: true,
    source: "IEBC declaration, August 2022 (top two)",
    results: [
      { name: "Johnson Sakaja (UDA)", votes: 699_392 },
      { name: "Polycarp Igathe (Jubilee)", votes: 573_516 },
    ],
    turnout: null,
    lessons: [
      "You won by 125,876 votes, and the outer estates carried it: Kasarani, Roysambu and Embakasi East.",
      "Westlands and Dagoretti North turned out least. In the model, each 5 points of turnout there is worth about 9,000 votes to you.",
      "Kibra, Mathare and Kamukunji went the other way. Cutting the gap there matters more than running up the score in Kasarani.",
    ],
  },
  diary: [
    {
      time: "06:30",
      place: "Kayole water point",
      kind: "Visit",
      why: "Answer the water story where it's loudest, before the breakfast shows end.",
    },
    {
      time: "09:30",
      place: "Water company and county water committee",
      kind: "Meeting",
      why: "Leave with a repair date you can announce.",
    },
    {
      time: "12:00",
      place: "Gikomba traders' association",
      kind: "Market",
      why: "Stall allocation has waited nine days; Kamukunji trails by 13.",
    },
    {
      time: "15:00",
      place: "County Assembly majority caucus",
      kind: "Meeting",
      why: "Line up the votes on parking fees before Tuesday.",
    },
    {
      time: "18:30",
      place: "Youth fellowship, Kibra",
      kind: "Church",
      why: "Your weakest constituency; church youth networks turn out.",
    },
  ],
  watch: [
    {
      level: "high",
      kind: "Misinformation",
      title: "Fake eviction notice for CBD hawkers on WhatsApp",
      detail:
        "A forged county letterhead, seen in 120 groups since 06:00. Post the real notice with a warning from the county's own accounts.",
    },
    {
      level: "medium",
      kind: "Weather",
      title: "Short rains may start two weeks early",
      detail:
        "Nine wards flooded last season. Drainage crews and a public schedule get ahead of it.",
    },
    {
      level: "medium",
      kind: "Security",
      title: "Matatu strike threat for Monday",
      detail:
        "If it goes ahead, expect gridlock and blame on City Hall. The termini decision is yours.",
    },
    {
      level: "low",
      kind: "IEBC",
      title: "Voter registration drive: 23 days left (demo dates)",
      detail: "180,000 unregistered 18–25s in Nairobi. The youth wing's target is 40,000.",
    },
    {
      level: "low",
      kind: "Money",
      title: "Spending: 32% of the legal limit",
      detail: "KES 138M so far. On pace for the calendar.",
    },
  ],
  night: {
    seed: 710,
    swing: { us: 1.6 },
    forms: { station: "Form 37A", levels: ["37B · constituency", "37C · county"] },
    incidents: [
      {
        at: "18:05",
        severity: "SEV-3",
        title: "Queues still at closing, 6 stations",
        area: "Embakasi East",
        detail: "Voters in line at 17:00 may vote; counting starts late.",
        status: "Logged",
      },
      {
        at: "19:20",
        severity: "SEV-2",
        title: "Agent sent out of a count",
        area: "Kamukunji",
        detail: "Evidence attached; the presiding officer has been told.",
        status: "→ Legal",
      },
      {
        at: "20:44",
        severity: "SEV-2",
        title: "A station ran out of forms",
        area: "Starehe",
        detail: "Replacements arrived at 21:03.",
        status: "Resolved 21:03",
      },
      {
        at: "22:02",
        severity: "SEV-3",
        title: "Crowd outside a tally centre",
        area: "Kasarani",
        detail: "Police present; tallying continues.",
        status: "Monitoring",
      },
    ],
    divergence: {
      at: "01:20",
      area: "Embakasi South",
      detail:
        "The portal shows 318 more votes for Challenger A at 2 stations than our photographed 37As. Sent for review.",
    },
  },
};
